project:
  type: website
  output-dir: _site

  preview:
    port: 5557
    browser: true
    watch-inputs: true
    navigate: true

  resources:
    - "photos/**"

brand: "brand/_brand.yml"

website:
  title: "Piyush Chaudhari"
  site-url: "https://pc-piyush.github.io/teaching"
  favicon: "photos/Piyush.png"
  search:
    location: navbar
    type: textbox
  twitter-card:
    creator: "@iampiyushvc"
  navbar:
    logo: "photos/PC_White.png"
    pinned: true
    right:
      - text: "Home"
        href: "https://pc-piyush.github.io"
      # - text: "CV"
      #   href: "https://pc-piyush.github.io/cv.html"
      # - text: "Research"
      #   href: "https://pc-piyush.github.io/research/"
      # - text: "Teaching"
      #   href: index.qmd
      # # - text: "Presentations"
      # #   href: "https://pc-piyush.github.io/presentations/"
      # - text: "p.log()"
      #   href: "https://pc-piyush.github.io/posts.html"
  page-footer:
    background: "#373a3c"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/piyush-chaudhari/
      - text: "{{< fa brands square-letterboxd >}}"
        url: "https://boxd.it/1uvEr"
    left: |
      <span class="faux-block"> Made with [Quarto](https://quarto.org/).</span>
      <span class="faux-block"> Piyush Chaudhari 2026</span>

format:
  html:
    theme:
      light: [brand, "html/dfb.scss"]
      dark: [brand, "html/dfb_dark.scss"]
    toc: true
    page-layout: full

editor: visual
